config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :admins
  resources :admin_sessions, only: [:new, :create, :destroy]
  get 'login' => 'admin_sessions#new'
  get 'logout' => 'admin_sessions#destroy'
  resources :admins, only: [:edit, :update]
  resources :posts, except: [:update, :edit]
  resources :posts do
    member do
      get :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  validates :username, :email, :password, :password_confirmation, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :tag

    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    validates :title, :made_by, :classroom, :category, :is_confirmed , presence: true

    def self.recent_posts
        Post.where("created_at >= ?", 1.week.ago.utc).order("created_at DESC")
    end

    def self.search(tag,category)
        if(tag=="" && category =="")
            where(nil)
        elsif(tag && category=="") 
            where('tag_id LIKE ?',"#{tag}")
        elsif(category && tag=="")
            where('category LIKE ?',"#{category}")
        elsif tag && category
            where('tag_id LIKE ?',"#{tag}").
            where('category LIKE ?',"#{category}")
        else
            where(nil)
        end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :posts
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
    layout false
    def new
    end

    def create
        if login(params[:email], params[:password])
          redirect_back_or_to(root_path)
        else
          render action: :new
        end
    end
    

    def destroy
        logout
        redirect_to(:root)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]
  layout 'administration'
  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include PostsHelper

    def index
        @current_week = Post.where("created_at >= ?", Date.today.at_beginning_of_week)
        @posts = Post.search(params[:tag],params[:category])
        @tags = Tag.all
    end 

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new

    end

    def create
        @post = Post.new(post_params)
        @post.is_confirmed = 0
        if @post.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def destroy 
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to root_path
    end

    def confirm
        post = Post.find(params[:id])
        post.is_confirmed = 1
        post.save

        redirect_to root_path
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        render dupa
    end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_params
        params.require(:post).permit(
            :title,
            :description,
            :made_by,
            :classroom,
            :category,
            :tag_id,
            :image)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin_sessions/new.html.erb
<h2>Login</h2>
<%=form_tag admin_sessions_path, method: :post do%>
    <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>

<%end%>

<%= link_to 'Back', root_path%>

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Zatwierdź"%>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Pokaż', @admin %> |
<%= link_to 'Wróć', admins_path %>

app/views/admins/index.html.erb
<h2>Administratorzy</h2>

<table>
  <thead>
    <tr>
      <th>Nazwa użytkownika</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.username %></td>
        <td><%= admin.email %></td>
        <td><%= link_to 'Pokaż', admin %></td>
        <td><%= link_to 'Edytuj', edit_admin_path(admin) %></td>
        <td><%= link_to 'Usuń', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj administratora', new_admin_path %>

app/views/admins/new.html.erb
<h2>Nowy administrator</h2>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p>
  <strong>Nazwa użytkownika</strong>
  <%= @admin.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Hasłó</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edytuj', edit_admin_path(@admin) %> |
<%= link_to 'Wróć', admins_path %>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Biuro Rzeczy Znalezionych | Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <h1>Panel Administratora</h1>
    <%if logged_in?%>
        <%=yield%>
        <br>
        <%if logged_in?%>
            <%="Zalogowany jako #{current_user.username}"%>
            <%=link_to "Wyloguj się", logout_path%>
        <%else%>
            <%=link_to "Zaloguj się", login_path%>
        <%end%>
    <%else%>
        <%=link_to "Wróć", root_path%>
    <%end%>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Biuro Rzeczy Znalezionych</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Biuro rzeczy znalezionych</h1>
    <%= yield %>
    <br>
    <%if logged_in?%>
      <%="Zalogowany jako #{current_user.username}"%>
      <%=link_to "Wyloguj się", logout_path%>
    <%else%>
      <%=link_to "Zaloguj się", login_path%>
    <%end%>
  </body>
</html>

app/views/posts/_adminfilter.html.erb
<%@posts.each do |post|%>
    <%=link_to post_path(post) do%>
        <div>
            <h3><%=post.title%></h3>
            <p>
                <%if post.image.exists?%>
                    <%= image_tag post.image.url%>
                <%end%>
            </p>
            <p>Opis: <%=post.description.truncate(30)%>...</p>
        </div>
    <%end%>
    <%if logged_in?%>
        <%=link_to "Zatwierdź", confirm_post_path(post)%>
    <%end%>
<%end%>

app/views/posts/_currentweek.html.erb
<%@current_week.each do |post|%>
     <%if post.is_confirmed == 1 %> 
        <%=link_to post_path(post) do%>
            <div>
                <h3><%=post.title%></h3>
                <p><%if post.image.exists?%>
                <%= image_tag post.image.url%>
                <%end%></p>
            </div>
        <%end%>
    <%end%>
<%end%>

app/views/posts/_filter.html.erb
<%@posts.each do |post|%>
    <div>
        <h3><%=post.title%></h3>
    </div>
<%end%>

app/views/posts/index.html.erb
<h2>Z ostatniego tygodnia</h2>
<%= render 'currentweek'%>
<h2>Wszystkie</h2>
<%= form_tag root_path, :method => 'get', :id => "category_select" do%>
    <%=select_tag(:tag, options_for_select([
    ['Elektronika'      ,1],
    ['Książki'          ,2],
    ['Zeszyty'          ,3],
    ['Przybory szkolne' ,4],
    ['Odzież'           ,5]
]),:include_blank => true)%>
    <%=select_tag(:category, options_for_select(
    [['Znaleziono',1],['Szukam',2]]
    ),:include_blank => true)%>
    <%=submit_tag "Search", :name => nil%>
<%end%>
<div id="filtered_posts">
<%if logged_in?%>
    <%= render :partial => "adminfilter"%>
<%else%>
    <%= render :partial => "filter"%>
<%end%>
</div>
<%=link_to "Dodaj nowy przedmiot", new_post_path%>

app/views/posts/index.js.erb
$("#filtered_posts").html("<%= escape_javascript(render("filter"))%>")

app/views/posts/new.html.erb
<h2>Dodawanie nowego przedmiotu</h2>
<%=form_for(@post, html: {multipart: true}) do |f|%>
<ul>
    <% @post.errors.full_messages.each do |error|%>
    <li><%=error%></li>
    <%end%>
</ul>
<p><%=f.label :title, "Tytuł"%></p>
<%= f.text_field :title%>

<p><%=f.label :image, "Dodaj obrazek (opcjonalne)"%></p>
<%=f.file_field :image%>

<p><%=f.label :description, "Opis"%></p>
<%= f.text_area :description%>

<p><%=f.label :made_by, "Autor"%></p>
<%=f.text_field :made_by%>

<p><%=f.label :classroom, "Gdzie"%></p>
<%=f.text_field :classroom%>

<p><%=f.label :tag_id, "Kategoria"%></p>
<%=f.select(:tag_id, options_for_select([
    ['Elektronika'      ,1],
    ['Książki'          ,2],
    ['Zeszyty'          ,3],
    ['Przybory szkolne' ,4],
    ['Odzież'           ,5]
]))%>

<p><%=f.label :category, "Zdarzenie"%></p>
<%=f.select(:category, options_for_select([['Znaleziono',1],['Szukam',2]]))%>

<%=f.submit%>
<%end%>

app/views/posts/show.html.erb
<h2><%=@post.title%></h2>
<p><%if @post.image.exists?%>
    <%= image_tag @post.image.url%>
<%end%></p>
<h3>Opis</h3>
<p><%=@post.description%></p>
<p>Sala: <%=@post.classroom%></p>
<p>Autor: <%=@post.made_by%></p>
<p>Data dodania: <%=@post.created_at%></p>
<%=link_to 'Usuń',post_path(@post), 
    method: :delete,
    data: {Confirm: 'Napewno?'}%>